/*USUWANIE REKORDÓW Z BAZY DANYCH*/
DELETE FROM WIZYTY;
DELETE FROM ZWIERZE;
DELETE FROM WLASCICIEL;
DELETE FROM ADRES;
DELETE FROM DIAGNOZA;
DELETE FROM ZABIEGI;
DELETE FROM LEKARZ;
DELETE FROM LEK;
DELETE FROM GATUNEK;
DELETE FROM BADANIA;
DELETE FROM MATERIALY;