


/* USUWANIE TABELI */
DROP TABLE WIZYTY
DROP TABLE DIAGNOZA
DROP TABLE ZABIEGI
DROP TABLE ZWIERZE
DROP TABLE GATUNEK
DROP TABLE WLASCICIEL
DROP TABLE ADRES
DROP TABLE LEKARZ
DROP TABLE LEK
DROP TABLE BADANIA
DROP TABLE MATERIALY

DROP FUNCTION dbo.DobreDane
